---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: eks-main
spec:
  forProvider:
    region: us-west-1
    cidrBlock: 10.10.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    tags:
      Name: eks-main